spring.application.name=springboot-security

spring.security.user.name=reza
spring.security.user.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/test_springboot_security
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update